#!/usr/bin/env bash
mkdir -p dist
echo "build src/ldcv.ls -> dist/ldcv.js ..."
./node_modules/.bin/lsc -cbp src/ldcv.ls > dist/ldcv.js
echo "build src/ldcv.styl -> dist/ldcv.css ..."
./node_modules/.bin/stylus -p src/ldcv.styl > dist/ldcv.css
echo "minifying ldcv.js ..."
./node_modules/.bin/uglifyjs dist/ldcv.js > dist/ldcv.min.js
echo "minifying ldcv.css ..."
./node_modules/.bin/uglifycss dist/ldcv.css > dist/ldcv.min.css
echo "Copy pug mixin to dist/ ..."
cp src/ldcv.pug dist/
echo "done."

